### ISSUE TITLE
Why is Typescript a full dependency of this module?

### ISSUE THREAD

**Issue by KingDGrizzle** [jakejrichards/cod-api#12]
Hello!

We've recently looked into your module, and it looks amazing. One thing that puzzled me is the fact that `typescript` is a dependency (not a dev-dependency).

Any reason for that decision?

Thanks!

**Comment by jakejrichards** [comment]
Hey @KingDGrizzle, thank you for the feedback and I'm glad that you like the package! I believe that you are correct that `typescript` should be a dev-dependency as it is only needed to build the project. I will go ahead change this.
