### ISSUE TITLE
how can i get blackout matches data?

### ISSUE THREAD

**Issue by cimpdev** [jakejrichards/cod-api#9]
how can i get blackout matches data?

**Comment by jakejrichards** [comment]
With version 4.0.0 I have added in a method called `BO4.getBlackoutMatchesStats` https://github.com/jakejrichards/cod-api/commit/3644e1698fe3ef6c409e76e62687d1fe13638621

**Comment by jaredfranka** [comment]
What is the end point for specific match data?
